name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop
strategy:
  matrix:
    go: ["1.14", "1.15"]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #pega os dados que foi atualizado, e atualiza na maquina ubunt
      - uses: actions/setup-go@v2 #prepara o ambiente para executar a linhagem GO
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go
# https://github.com/actions/checkout
# https://github.com/actions/setup-go
